use strict;
use warnings;
use myUtils::PhobiusService;

my %secuencias = ('ins' => 'MALWMRLLPLLALLALWGPDPAAAFVNQHLCGSHLVEALYLVCGERGFFYTPKTRREAEDLQVGQVELGGGPGAGSLQPLALEGSLQKRGIVEQCCTSICSLYQLENYCN');

my %secuencias1 = (
		  'mutated_seq' => 'MLYFQMVIMAGTVMLAYYFEYTDTFTVNVQGFFCHDSAYRKPYPGPEDSSAVPPVLLYSLAAGVPVLVIIVGETAVFCLQLATRDFENQEKTILTGDCCYINPLVRRTVRFLGIYTFGLFATDIFVNAGQVVTGNLAPHFLALCKPNYTALGCQQYTQFISGEEACTGNPDLIMRARKTFPSKEAALSVYAAMYLTMYITNTIKAKGTRLAKPVLCLGLMCLAFLTGLNRVAEYRNHWSDVIAGFLVGISIAVFLVVCVVNNFKGRQAENEHIHMDNLAQMPMISIPRVESPLEKNHITAFAEVT',
		);

my %secuencias2 = (
		  'original_seq' => 'MPLLPAALTSSMLYFQMVIMAGTVMLAYYFEYTDTFTVNVQGFFCHDSAYRKPYPGPEDSSAVPPVLLYSLAAGVPVLVIIVGETAVFCLQLATRDFENQEKTILTGDCCYINPLVRRTVRFLGIYTFGLFATDIFVNAGQVVTGNLAPHFLALCKPNYTALGCQQYTQFISGEEACTGNPDLIMRARKTFPSKEAALSVYAAMYLTMYITNTIKAKGTRLAKPVLCLGLMCLAFLTGLNRVAEYRNHWSDVIAGFLVGISIAVFLVVCVVNNFKGRQAENEHIHMDNLAQMPMISIPRVESPLEKNHITAFAEVT',
		);

#print myUtils::PhobiusService::hash_to_fasta(\%secuencias);
my %results = myUtils::PhobiusService::get_info_signal_peptide(\%secuencias);
# myUtils::PhobiusService::get_info_signal_peptide(\%secuencias1);
# myUtils::PhobiusService::get_info_signal_peptide(\%secuencias2);

foreach my $feature (@{$results{'ins'}}){
	print $feature->{'TYPE'} . " " . $feature->{'START'} . " " . $feature->{'END'} . " " . $feature->{'LOCATION'} . "\n";
}
