use strict;
use warnings;
use myUtils::PhobiusService;

my %secuencias = ('ins' => 'MALWMRLLPLLALLALWGPDPAAAFVNQHLCGSHLVEALYLVCGERGFFYTPKTRREAEDLQVGQVELGGGPGAGSLQPLALEGSLQKRGIVEQCCTSICSLYQLENYCN',
                                        'serpinc1' => 'MYSNVIGTVTSGKRKVYLLSLLLIGFWDCVTCHGSPVDICTAKPRDIPMNPMCIYRSPEKKATEDEGSEQKIPEATNRRVWELSKANSRFATTFYQHLADSKNDNDNIFLSPLSISTAFAMTKLGACNDTLQQLMEVFKFDTISEKTSDQIHFFFAKLNCRLYRKANKSSKLVSANRLFGDKSLTFNETYQDISELVYGAKLQPLDFKENAEQSRAAINKWVSNKTEGRITDVIPSEAINELTVLVLVNTIYFKGLWKSKFSPENTRKELFYKADGESCSASMMYQEGKFRYRRVAEGTQVLELPFKGDDITMVLILPKPEKSLAKVEKELTPEVLQEWLDELEEMMLVVHMPRFRIEDGFSLKEQLQDMGLVDLFSPEKSKLPGIVAEGRDDLYVSDAFHKAFLEVNEEGSEAAASTAV');

my %secuencias2 = ('ins' => 'MALWMRLLPLLALLALWGPDPAAAFVNQHLCGSHLVEALYLVCGERGFFYTPKTRREAEDLQVGQVELGGGPGAGSLQPLALEGSLQKRGIVEQCCTSICSLYQLENYCN');


#print myUtils::PhobiusService::hash_to_fasta(\%secuencias);
my %results = %{myUtils::PhobiusService::get_info_signal_peptide_local(\%secuencias2)};

foreach my $feature (@{$results{'ins'}}){
	print $feature->{'TYPE'} . " " . $feature->{'START'} . " " . $feature->{'END'} . " " . $feature->{'LOCATION'} . "\n";
}

print "\n\n";
foreach my $feature (@{$results{'serpinc1'}}){
	print $feature->{'TYPE'} . " " . $feature->{'START'} . " " . $feature->{'END'} . " " . $feature->{'LOCATION'} . "\n";
}