use strict;
use warnings;
use Bio::EnsEMBL::Registry;
use myUtils::SeqUtils;
use v5.10.0;


my $MET = 'ATG';
my $seq1 = 'ATGCTCATTATGCTCCAAATCTAA';
my $seq2 = 'ATGCTCCAAATCTAA';
my $seq3 = 'ATGCGGCAGCATGAATAA';
my $seq4 = 'ATGAATAACTAA';



# say myUtils::SeqUtils::get_translation($seq1);
# say myUtils::SeqUtils::get_translation($seq2);

# say myUtils::SeqUtils::get_orf($seq1, 0);

if (myUtils::SeqUtils::is_in_frame($seq1, $seq2)){
    say "TEST PASS";
} else {
    say "TEST FAIL";
}

if (myUtils::SeqUtils::is_in_frame($seq2, $seq1)){
    say "TEST PASS";
} else {
    say "TEST FAIL";
}

if (myUtils::SeqUtils::is_in_frame($seq3, $seq4)){
    say "TEST FAIL";
} else {
    say "TEST PASS";
}

if (myUtils::SeqUtils::is_in_frame($seq4, $seq3)){
    say "TEST FAIL";
} else {
    say "TEST PASS";
}

if ($seq1 eq myUtils::SeqUtils::get_orf($seq1, 0)){
    say "TEST PASS";
} else{
    say "TEST FAIL";
}

if ($seq2 eq myUtils::SeqUtils::get_orf($seq1, 1)){
    say "TEST PASS";
} else{
    say "TEST FAIL";
}

if (!defined(myUtils::SeqUtils::get_orf($seq1, 90))){
    say "TEST PASS";
} else {
    say "TEST FAIL";
}

if (!defined(myUtils::SeqUtils::get_orf('AAAAAAAAAAAAA', 90))){
    say "TEST PASS";
} else {
    say "TEST FAIL";
}

if ($seq3 eq myUtils::SeqUtils::get_orf($seq3, 0)){
    say "TEST PASS";
} else{
    say "TEST FAIL";
}

if ('ATGAATAA' eq myUtils::SeqUtils::get_orf($seq3, 1)){
    say "TEST PASS";
} else{
    say "TEST FAIL";
}

print "\n\n\n\n\n\n";

my $cdna = 'TTTTTTTTATTTTATGCAAGAAACGAGCATGCAACCCAAAGGGTAGTTTTTTTTTTTTTTTTTT';
my $cds = 'ATGCAAGAAACGAGCATGCAACCCAAAGGGTAG';

my $mut1 = 'TTTTTTTTATTTTATCCAAGAAACGAGCATGCAACCCAAAGGGTAGTTTTTTTTTTTTTTTTTT';
my $hashref = myUtils::SeqUtils::get_met_mutation_info($cdna, $cds, $mut1, 0);
if ($hashref->{first_met_position} == 15 && $hashref->{stop_codon_position} == 30 && $hashref->{reading_frame} eq 'Conserved'){
    say "TEST PASS";
} else {
    say "TEST FAIL";
}

my $mut2 = 'TTTTTTTTATTTGCAAGAAACGAGCATGCAACCCAAAGGGTAGTTTTTTTTTTTTTTTTTT';
$hashref = myUtils::SeqUtils::get_met_mutation_info($cdna, $cds, $mut2, 1);
if ($hashref->{first_met_position} == 15 && $hashref->{stop_codon_position} == 30 && $hashref->{reading_frame} eq 'Conserved'){
    say "TEST PASS";
} else {
    say "TEST FAIL";
}

my $mut3 = 'TTTTTTTTATGCAAGAAACGAGCATGCAACCCAAAGGGTAGTTTTTTTTTTTTTTTTTT';
$hashref = myUtils::SeqUtils::get_met_mutation_info($cdna, $cds, $mut3, 1);
if ($hashref->{first_met_position} == 0 && $hashref->{stop_codon_position} == 30 && $hashref->{reading_frame} eq 'Conserved'){
    say "TEST PASS";
} else {
    say "TEST FAIL";
}


my $mut4 = 'TTTTTTTTATTTTACAAGAAACGAGCATGCAACCCAAAGGGTAGTTTTTTTTTTTTTTTTTT';
$hashref = myUtils::SeqUtils::get_met_mutation_info($cdna, $cds, $mut4, 0);
if ($hashref->{first_met_position} == 15 && $hashref->{stop_codon_position} == 30 && $hashref->{reading_frame} eq 'Conserved'){
    say "TEST PASS";
} else {
    say "TEST FAIL";
}

my $cdna2 = 'GAGACGGCCTTGGCCGGACTTAGCACTCAGGCCTGTGAATCAGGAGATACAAAGACCTCCAAAAAAGGACCAGTTCCTCGGATGTGCCCCCTCACAGAGAGATGAAGGGGTGAGTGAAGAAGAGGCAGCAGAAAACAGCTGAAACGGAAGAGGGGACAGTGCAGATTCAGGAAGGTGCAGTGGCTACTGGGGAAGACCCAACCAGTGTGGCTATTGCCAGCATCCAGTCAGCTGCCACCTTCCCTGACCCCAACGTCAAGTACGTCTTCCGAACTGAGAATGGGGGCCAGGTGATGTACAGGGTGATCCAGGTGTCTGAGGGGCAGCTGGATGGCCAAACTGAGGGAACTGGCGCCATCAGTGGCTACCCTGCCACTCAATCCATGACCCAGGCGGTGATCCAGGGTGCTTTCACCAGTGATGATGCAGTTGACACGGAGGGGACAGCTGCTGAGACGCACTATACTTACTTCCCCAGCACGGCAGTGGGAGATGGGGCAGGGGGTACCACATCGGGGAGTACAGCTGCTGTTGTTACTACCCAGGGCTCAGAGGCACTGCTGGGGCAGGCGACCCCTCCTGGCACTGGTCAATTCTTTGTGATGATGTC';
my $cds2 = 'ATGTACAGGGTGATCCAGGTGTCTGAGGGGCAGCTGGATGGCCAAACTGAGGGAACTGGCGCCATCAGTGGCTACCCTGCCACTCAATCCATGACCCAGGCGGTGATCCAGGGTGCTTTCACCAGTGATGATGCAGTTGACACGGAGGGGACAGCTGCTGAGACGCACTATACTTACTTCCCCAGCACGGCAGTGGGAGATGGGGCAGGGGGTACCACATCGGGGAGTACAGCTGCTGTTGTTACTACCCAGGGCTCAGAGGCACTGCTGGGGCAGGCGACCCCTCCTGGCACTGGTCAATTCTTTGTGATGATGTC';
my $mut5 = 'GAGACGGCCTTGGCCGGACTTAGCACTCAGGCCTGTGAATCAGGAGATACAAAGACCTCCAAAAAAGGACCAGTTCCTCGGATGTGCCCCCTCACAGAGAGATGAAGGGGTGAGTGAAGAAGAGGCAGCAGAAAACAGCTGAAACGGAAGAGGGGACAGTGCAGATTCAGGAAGGTGCAGTGGCTACTGGGGAAGACCCAACCAGTGTGGCTATTGCCAGCATCCAGTCAGCTGCCACCTTCCCTGACCCCAACGTCAAGTACGTCTTCCGAACTGAGAATGGGGGCCAGGTGATGATGTACAGGGTGATCCAGGTGTCTGAGGGGCAGCTGGATGGCCAAACTGAGGGAACTGGCGCCATCAGTGGCTACCCTGCCACTCAATCCATGACCCAGGCGGTGATCCAGGGTGCTTTCACCAGTGATGATGCAGTTGACACGGAGGGGACAGCTGCTGAGACGCACTATACTTACTTCCCCAGCACGGCAGTGGGAGATGGGGCAGGGGGTACCACATCGGGGAGTACAGCTGCTGTTGTTACTACCCAGGGCTCAGAGGCACTGCTGGGGCAGGCGACCCCTCCTGGCACTGGTCAATTCTTTGTGATGATGTC';

$hashref = myUtils::SeqUtils::get_met_mutation_info($cdna2, $cds2, $mut5, 0);
if ($hashref->{first_met_position} == 0 && $hashref->{stop_codon_position} eq 'No Stop' && $hashref->{reading_frame} eq 'Conserved'){
    say "TEST PASS";
} else {
    say "TEST FAIL";
}


my $cdna3 = 'CCCCCCCCCCCCCCCCCCCCCCCCCATGCAACAACAACAACAACAATAGTTTTTTTTTTTTTTTTTTTTTTT';
my $cds3 = 'ATGCAACAACAACAACAACAATAG';
my $mut6 = 'CCCCCCCCCCCCCCCCCCCCCCCCCATGATGCAACAACAACAACAACAATAGTTTTTTTTTTTTTTTTTTTTTTT';
$hashref = myUtils::SeqUtils::get_met_mutation_info($cdna3, $cds3, $mut6, 0);
if ($hashref->{first_met_position} == 0 && $hashref->{stop_codon_position} == 21&& $hashref->{reading_frame} eq 'Conserved'){
    say "TEST PASS";
} else {
    say "TEST FAIL";
}


my $mut7 = 'CCCCCCCCCCCCCCCCCCCCCCCCCAATGCAACAACAACAACAACAATAGTTTTTTTTTTTTTTTTTTTTTTT';
$hashref = myUtils::SeqUtils::get_met_mutation_info($cdna3, $cds3, $mut7, 0);
if ($hashref->{first_met_position} == 0 && $hashref->{stop_codon_position} == 21&& $hashref->{reading_frame} eq 'Conserved'){
    say "TEST PASS";
} else {
    say "TEST FAIL";
}

my $mut8 = 'CCCCCCCCCCCCCCCCCCCCCCCCCATTGCAACAACAACAACAACAATAGTTTTTTTTTTTTTTTTTTTTTTT';
$hashref = myUtils::SeqUtils::get_met_mutation_info($cdna3, $cds3, $mut8, 0);
if ($hashref->{first_met_position} eq '' && $hashref->{stop_codon_position} eq ''&& $hashref->{reading_frame} eq ''){
    say "TEST PASS";
} else {
    say "TEST FAIL";
}

my $cdna4 = 'CCCCCCCCCCCCCCCCCCCCCCCCCATGCAACAACAATGACAACAACATAGTTTTTTTTTTTTTTTTTTTTTTT';
my $cds4 = 'ATGCAACAACAATGACAACAACATAG';
my $mut9 = 'CCCCCCCCCCCCCCCCCCCCCCCCCATTGCAACAACAATGACAACAACATAGTTTTTTTTTTTTTTTTTTTTTTT';
$hashref = myUtils::SeqUtils::get_met_mutation_info($cdna4, $cds4, $mut9, 0);
if ($hashref->{first_met_position} == 11 && $hashref->{stop_codon_position} == 23&& $hashref->{reading_frame} eq 'Lost'){
    say "TEST PASS";
} else {
    say "TEST FAIL";
}

my $cdna5 = 'ATTAGTTCAGGGAAGGACTTGCTCACCTGCTCCTCCCCTCTGACTCAAGTCATAACAAGTAACCTGGTTCCCCTGGCCCGGCAGCCTGGGAGGGACGGCAAGGTAGGCAGGTGAGCCGAGACGGACGGACGGCCAGCAGCTCCGTCAGCTGGAGAGAGAGCACAGGCCTGTGGCTTGGGAGACCCTGAGGCGACATGTGAGGGCCCTGAGCCCCCTGACTGGAAGCAGGGGCTGTTTTTCAACTCCTGGACTAAAGCCCAGAAGCAGCTGGGGAAGCTCCAGGCTACCTACACAACCTGGCCCAGGCTGGTCACGGTGTCCCCCCTCCCTGCTCTGTGCCCTCTCCTTCCAGAAATCCACCATGGAGAGTAAGGATGAGGTCAGCGACACCGACAGTGGCATCATCCTGCAGTCTGGCCCCGACAGCCCGGTCTCCCCAATGAAGGAGCTGACCCATGCAGTGCACAAGCAGCAGAGGGCCCTGGAAGCGAGGCTGGAGGCCTGCCTGGAGGAGCTGAGGAGACTCTGCCTTCGGGAAGCGGAGCTGACGGGCACCTTGCCAGCGGAGTATCCCCTCAAACCAGGGGAAAAGGCCCCCAAGGTTCGCCGCAGGATCGGAGCGGCTTACAAACTGGATGACTGGGCCTTGCACAGAGAGGACCCCCTAAGCAGCCTGGAGCGCCAGCTGGCCCTGCAGCTGCAGATCACAGAGGCAGCCCGTCGGCTGTGCCTGGAGGAGAACCTCAGCAGGCAGGCTCGGCGGCAGCGGAAGCACTCCATGCTGCAGGAGGAGAAGAAGCTGCAGGAGCTCCAGCGCTGCCTGGTCGAGCGGCGGCGCAATAGCGAGCCACCTCCGGCTGCTGCTCTCCCCCTGGGCCGAGAGCTCAGTGCCTCTGATGACAGCTCCCTGTCAGATGGGCTCCTCCTGGAGGAAGAGGAATCCCAAGTGCCAAAACCTCCTCCAGAGTCTCCAGCCCCACCTTCTCGGCCTCTCCCACCCCAAACCCTTGAGGGTCTGCAGCCAACAGGACCTGAGGCTGGGAGCCCAGAACGGGCTCCAGTCCAGAACAGCCCCTGGAAGGAAACCAGCCTGGACCACCCCTATGAGAAGCCCAGGAAGTCTTCTGAGCCCTGGAGCGAGTCCAGCAGCCCAGCCACCACACCACAGGATGGGCCCAGTGCCTCCAGCCTGTGGCTTCTGGAGCCTGCCTCCTACCACGTGGTTCCCATCCGTGGTGTTCCTGGCCAGTGGCAGGGCCGCACCAGTGCCCCAGCCACCCCTGAGATACAGGGGAGGAGGGGCCAGTCGCAGTCTCTGAGGGTGGATTCCTTCCGGGCGGGTCCTGAGGGCCGAGGTCGCAGCGCCTTTCCCCGCCGCCGCCCCACTCACTACACGGTGACAGTGCCAGATTCCTGCTTTCCCGCGACCAAGCCCCCGCTGCCCCACGCCGCCTGCCACTCCTGCTCAGAAGACAGTGGCTCTGACGTCTCCAGCATCTCCCACCCCACTTCGCCGGGCAGCAGCAGCCCCGACATCTCCTTTCTGCAGCCTCTCTCCCCTCCCAAGACCCATCGTCACCGCGGGGCCTGGGTCCCAGCCGGCAGCAGAGAGCTGGTCGCCCACCACCCCAAGCTACTGCTGCCGCCTGGCTATTTCCCGGCGGGGCGGTACGTGGTGGTGGCTGAGAGCCCCCTGCCGCCTGGCGAGTGGGAGCTGCGCCGCGCAGCCCCGGGCCCTGCTTACGAGGAGGAGGGCACTCCCCTGCGCTACCAGCGTCTGGTGCCCTCCCGCAGCCGCATCGTGCGGACGCCCTCCCTGAAGGACAGCCCGGCAGGCCGGGGGCTCAGCAAGGCCGCCGTGTCCGAGGAGCTCAAGTGGTGGCACGAGCGTGCACGCCTCCGGAGCACCCGCCCCCACTCACTGGACCGCCAAGGAGCTTTCCGGGTCAGGAGCCTGCCCCTTGGGAGAGAGGGCTTCGGACGAGCCCTGGGACCCCGGGCACAGGTGCCCACAGTTTGTGTGCTGCGGAGATCGCCTGATGGGGCCCCTGTGCAAGTCTTTGTACCTGAAAAAGGAGAGATCATCAGCCAGGTGTAACTCTGCGCCCCACGCTGGAAAAAACTGTTTCATAGAGGGGCTGGGCTGAGACCCCCCCACCCCTGAGTGCCTCTTTCAGCTCCCCCATCCCCATCGCAG';
my $cds5 = 'ATGGAGAGTAAGGATGAGGTCAGCGACACCGACAGTGGCATCATCCTGCAGTCTGGCCCCGACAGCCCGGTCTCCCCAATGAAGGAGCTGACCCATGCAGTGCACAAGCAGCAGAGGGCCCTGGAAGCGAGGCTGGAGGCCTGCCTGGAGGAGCTGAGGAGACTCTGCCTTCGGGAAGCGGAGCTGACGGGCACCTTGCCAGCGGAGTATCCCCTCAAACCAGGGGAAAAGGCCCCCAAGGTTCGCCGCAGGATCGGAGCGGCTTACAAACTGGATGACTGGGCCTTGCACAGAGAGGACCCCCTAAGCAGCCTGGAGCGCCAGCTGGCCCTGCAGCTGCAGATCACAGAGGCAGCCCGTCGGCTGTGCCTGGAGGAGAACCTCAGCAGGCAGGCTCGGCGGCAGCGGAAGCACTCCATGCTGCAGGAGGAGAAGAAGCTGCAGGAGCTCCAGCGCTGCCTGGTCGAGCGGCGGCGCAATAGCGAGCCACCTCCGGCTGCTGCTCTCCCCCTGGGCCGAGAGCTCAGTGCCTCTGATGACAGCTCCCTGTCAGATGGGCTCCTCCTGGAGGAAGAGGAATCCCAAGTGCCAAAACCTCCTCCAGAGTCTCCAGCCCCACCTTCTCGGCCTCTCCCACCCCAAACCCTTGAGGGTCTGCAGCCAACAGGACCTGAGGCTGGGAGCCCAGAACGGGCTCCAGTCCAGAACAGCCCCTGGAAGGAAACCAGCCTGGACCACCCCTATGAGAAGCCCAGGAAGTCTTCTGAGCCCTGGAGCGAGTCCAGCAGCCCAGCCACCACACCACAGGATGGGCCCAGTGCCTCCAGCCTGTGGCTTCTGGAGCCTGCCTCCTACCACGTGGTTCCCATCCGTGGTGTTCCTGGCCAGTGGCAGGGCCGCACCAGTGCCCCAGCCACCCCTGAGATACAGGGGAGGAGGGGCCAGTCGCAGTCTCTGAGGGTGGATTCCTTCCGGGCGGGTCCTGAGGGCCGAGGTCGCAGCGCCTTTCCCCGCCGCCGCCCCACTCACTACACGGTGACAGTGCCAGATTCCTGCTTTCCCGCGACCAAGCCCCCGCTGCCCCACGCCGCCTGCCACTCCTGCTCAGAAGACAGTGGCTCTGACGTCTCCAGCATCTCCCACCCCACTTCGCCGGGCAGCAGCAGCCCCGACATCTCCTTTCTGCAGCCTCTCTCCCCTCCCAAGACCCATCGTCACCGCGGGGCCTGGGTCCCAGCCGGCAGCAGAGAGCTGGTCGCCCACCACCCCAAGCTACTGCTGCCGCCTGGCTATTTCCCGGCGGGGCGGTACGTGGTGGTGGCTGAGAGCCCCCTGCCGCCTGGCGAGTGGGAGCTGCGCCGCGCAGCCCCGGGCCCTGCTTACGAGGAGGAGGGCACTCCCCTGCGCTACCAGCGTCTGGTGCCCTCCCGCAGCCGCATCGTGCGGACGCCCTCCCTGAAGGACAGCCCGGCAGGCCGGGGGCTCAGCAAGGCCGCCGTGTCCGAGGAGCTCAAGTGGTGGCACGAGCGTGCACGCCTCCGGAGCACCCGCCCCCACTCACTGGACCGCCAAGGAGCTTTCCGGGTCAGGAGCCTGCCCCTTGGGAGAGAGGGCTTCGGACGAGCCCTGGGACCCCGGGCACAGGTGCCCACAGTTTGTGTGCTGCGGAGATCGCCTGATGGGGCCCCTGTGCAAGTCTTTGTACCTGAAAAAGGAGAGATCATCAGCCAGGTGTAA';
my $mut10 = 'ATTAGTTCAGGGAAGGACTTGCTCACCTGCTCCTCCCCTCTGACTCAAGTCATAACAAGTAACCTGGTTCCCCTGGCCCGGCAGCCTGGGAGGGACGGCAAGGTAGGCAGGTGAGCCGAGACGGACGGACGGCCAGCAGCTCCGTCAGCTGGAGAGAGAGCACAGGCCTGTGGCTTGGGAGACCCTGAGGCGACATGTGAGGGCCCTGAGCCCCCTGACTGGAAGCAGGGGCTGTTTTTCAACTCCTGGACTAAAGCCCAGAAGCAGCTGGGGAAGCTCCAGGCTACCTACACAACCTGGCCCAGGCTGGTCACGGTGTCCCCCCTCCCTGCTCTGTGCCCTCTCCTTCCAGAAATCCACCATGGATGAGGTCAGCGACACCGACAGTGGCATCATCCTGCAGTCTGGCCCCGACAGCCCGGTCTCCCCAATGAAGGAGCTGACCCATGCAGTGCACAAGCAGCAGAGGGCCCTGGAAGCGAGGCTGGAGGCCTGCCTGGAGGAGCTGAGGAGACTCTGCCTTCGGGAAGCGGAGCTGACGGGCACCTTGCCAGCGGAGTATCCCCTCAAACCAGGGGAAAAGGCCCCCAAGGTTCGCCGCAGGATCGGAGCGGCTTACAAACTGGATGACTGGGCCTTGCACAGAGAGGACCCCCTAAGCAGCCTGGAGCGCCAGCTGGCCCTGCAGCTGCAGATCACAGAGGCAGCCCGTCGGCTGTGCCTGGAGGAGAACCTCAGCAGGCAGGCTCGGCGGCAGCGGAAGCACTCCATGCTGCAGGAGGAGAAGAAGCTGCAGGAGCTCCAGCGCTGCCTGGTCGAGCGGCGGCGCAATAGCGAGCCACCTCCGGCTGCTGCTCTCCCCCTGGGCCGAGAGCTCAGTGCCTCTGATGACAGCTCCCTGTCAGATGGGCTCCTCCTGGAGGAAGAGGAATCCCAAGTGCCAAAACCTCCTCCAGAGTCTCCAGCCCCACCTTCTCGGCCTCTCCCACCCCAAACCCTTGAGGGTCTGCAGCCAACAGGACCTGAGGCTGGGAGCCCAGAACGGGCTCCAGTCCAGAACAGCCCCTGGAAGGAAACCAGCCTGGACCACCCCTATGAGAAGCCCAGGAAGTCTTCTGAGCCCTGGAGCGAGTCCAGCAGCCCAGCCACCACACCACAGGATGGGCCCAGTGCCTCCAGCCTGTGGCTTCTGGAGCCTGCCTCCTACCACGTGGTTCCCATCCGTGGTGTTCCTGGCCAGTGGCAGGGCCGCACCAGTGCCCCAGCCACCCCTGAGATACAGGGGAGGAGGGGCCAGTCGCAGTCTCTGAGGGTGGATTCCTTCCGGGCGGGTCCTGAGGGCCGAGGTCGCAGCGCCTTTCCCCGCCGCCGCCCCACTCACTACACGGTGACAGTGCCAGATTCCTGCTTTCCCGCGACCAAGCCCCCGCTGCCCCACGCCGCCTGCCACTCCTGCTCAGAAGACAGTGGCTCTGACGTCTCCAGCATCTCCCACCCCACTTCGCCGGGCAGCAGCAGCCCCGACATCTCCTTTCTGCAGCCTCTCTCCCCTCCCAAGACCCATCGTCACCGCGGGGCCTGGGTCCCAGCCGGCAGCAGAGAGCTGGTCGCCCACCACCCCAAGCTACTGCTGCCGCCTGGCTATTTCCCGGCGGGGCGGTACGTGGTGGTGGCTGAGAGCCCCCTGCCGCCTGGCGAGTGGGAGCTGCGCCGCGCAGCCCCGGGCCCTGCTTACGAGGAGGAGGGCACTCCCCTGCGCTACCAGCGTCTGGTGCCCTCCCGCAGCCGCATCGTGCGGACGCCCTCCCTGAAGGACAGCCCGGCAGGCCGGGGGCTCAGCAAGGCCGCCGTGTCCGAGGAGCTCAAGTGGTGGCACGAGCGTGCACGCCTCCGGAGCACCCGCCCCCACTCACTGGACCGCCAAGGAGCTTTCCGGGTCAGGAGCCTGCCCCTTGGGAGAGAGGGCTTCGGACGAGCCCTGGGACCCCGGGCACAGGTGCCCACAGTTTGTGTGCTGCGGAGATCGCCTGATGGGGCCCCTGTGCAAGTCTTTGTACCTGAAAAAGGAGAGATCATCAGCCAGGTGTAACTCTGCGCCCCACGCTGGAAAAAACTGTTTCATAGAGGGGCTGGGCTGAGACCCCCCCACCCCTGAGTGCCTCTTTCAGCTCCCCCATCCCCATCGCAG';
$hashref = myUtils::SeqUtils::get_met_mutation_info($cdna5, $cds5, $mut10, 0);
if ($hashref->{first_met_position} == 0 && $hashref->{stop_codon_position} == 1734&& $hashref->{reading_frame} eq 'Conserved'){
    say "TEST PASS";
} else {
    say "TEST FAIL";
}


my $cdna6 = 'GAGAGAGAATGACCCAAGCCCGGTAGAGAGAGAGAGA';
my $cds6 = 'ATGACCCAAGCCCGGTAG';
my $mut11 = 'GAGAGAGAATGGGGACCCAAGCCCGGTAGAGAGAGAGAGA';
$hashref = myUtils::SeqUtils::get_met_mutation_info($cdna6, $cds6, $mut11, 0);
if ($hashref->{first_met_position} == 0 && $hashref->{stop_codon_position} == 15&& $hashref->{reading_frame} eq 'Conserved'){
    say "TEST PASS";
} else {
    say "TEST FAIL";
}


my $cdna7 = 'GAGAGAGAATGACCCAAGCCCGGTAGAGAGAGAGAGA';
my $cds7 = 'ATGACCCAAGCCCGGTAG';
my $mut12 = 'GAGAGAGAATGGGACCCAAGCCCGGTAGAGAGAGAGAGA';
$hashref = myUtils::SeqUtils::get_met_mutation_info($cdna7, $cds7, $mut12, 0);
if ($hashref->{first_met_position} == 0 && $hashref->{stop_codon_position} eq 'No Stop' && $hashref->{reading_frame} eq 'Lost'){
    say "TEST PASS";
} else {
    say "TEST FAIL";
}


my $cdna8 = 'GGCATGGCGGCCAGGCAGATCTGGGCACGGACGGGTGCCGCGCTCTGCAGGCAACCTTCCGCCGCCCCGCCGCCAGCACCTCTCTGGGTAAGAGCTGGGTTCCGACAGCAGCTCAGCTTAACCCTCTGCCCTGCTAACGAGGGAAACTGCGGCGGCTCCGCGCCCAGCACGCCCGGTAGGCCGGAGAGAGCGGCGAGGCCTTCGGTGAGCGAAGAGTTAACCGCGGCGGAGCGACAGATCGCGGAGCTGCACGCTGCCGCCTGCGCGGCTGGCCAGCTAAACTATGTGGATCCAGCTACTGGCTATGTGGTGCTCACACAGATTGCCCACTTGCAAAGAGGTGAATGTTGTGGCTCTGCGTGCAGACATTGTCCATATGGTCAAGTCAATGTTAAAGATCCATCTAAAAAGAAGCAATTCAATTCATATTTTTATGTTTGACAAGAATTTCATCTCTGTTCCCTAACTGTGCTTGTATTTTTTAAAAAATAAAGCCCCAATTCAGAATTGCTGGATTATTAGTACTTGAACACTAGTTTAATCCTAAATACATATATTAAAAGAACATCAATAAAATGAAAAAGCTAA';
my $cds8 = 'ATGGCGGCCAGGCAGATCTGGGCACGGACGGGTGCCGCGCTCTGCAGGCAACCTTCCGCCGCCCCGCCGCCAGCACCTCTCTGGGTAAGAGCTGGGTTCCGACAGCAGCTCAGCTTAACCCTCTGCCCTGCTAACGAGGGAAACTGCGGCGGCTCCGCGCCCAGCACGCCCGGTAGGCCGGAGAGAGCGGCGAGGCCTTCGGTGAGCGAAGAGTTAACCGCGGCGGAGCGACAGATCGCGGAGCTGCACGCTGCCGCCTGCGCGGCTGGCCAGCTAAACTATGTGGATCCAGCTACTGGCTATGTGGTGCTCACACAGATTGCCCACTTGCAAAGAGGTGAATGTTGTGGCTCTGCGTGCAGACATTGTCCATATGGTCAAGTCAATGTTAAAGATCCATCTAAAAAGAAGCAATTCAATTCATATTTTTATGTTTGA';
my $mut13 = 'GGCCTGGCGGCCAGGCAGATCTGGGCACGGACGGGTGCCGCGCTCTGCAGGCAACCTTCCGCCGCCCCGCCGCCAGCACCTCTCTGGGTAAGAGCTGGGTTCCGACAGCAGCTCAGCTTAACCCTCTGCCCTGCTAACGAGGGAAACTGCGGCGGCTCCGCGCCCAGCACGCCCGGTAGGCCGGAGAGAGCGGCGAGGCCTTCGGTGAGCGAAGAGTTAACCGCGGCGGAGCGACAGATCGCGGAGCTGCACGCTGCCGCCTGCGCGGCTGGCCAGCTAAACTATGTGGATCCAGCTACTGGCTATGTGGTGCTCACACAGATTGCCCACTTGCAAAGAGGTGAATGTTGTGGCTCTGCGTGCAGACATTGTCCATATGGTCAAGTCAATGTTAAAGATCCATCTAAAAAGAAGCAATTCAATTCATATTTTTATGTTTGACAAGAATTTCATCTCTGTTCCCTAACTGTGCTTGTATTTTTTAAAAAATAAAGCCCCAATTCAGAATTGCTGGATTATTAGTACTTGAACACTAGTTTAATCCTAAATACATATATTAAAAGAACATCAATAAAATGAAAAAGCTAA';
$hashref = myUtils::SeqUtils::get_met_mutation_info($cdna8, $cds8, $mut13, 0);
if ($hashref->{first_met_position} == 280 && $hashref->{reading_frame} eq 'Lost'){
    say "TEST PASS";
} else {
    say "TEST FAIL";
}
